Fix error with last version (Compat 241)
silvasur/idea_caseconv pull request #7
Opened 2024-04-05 11:46 UTC by d3v2a

- Migrate to new plugin structure
 - Fix error with ActionUpdateThread
 - Add icon from https://www.svgrepo.com

2024-04-19 22:31 UTC, silvasur requested changes
Thanks for the pull request, this fixes the deprecation error. Please check the comments for the individual files.

2024-04-19 22:31 UTC, silvasur commented on gradle/wrapper/gradle-wrapper.jar
How was this file generated? I tried to run `gradle wrapper` with gradle version 8.6 and got a different JAR in the end? How can I verify that this file is legit?

2024-04-19 22:31 UTC, silvasur commented on build.gradle.kts
> +    version.set("2023.2.5")
Hmm, is there a way to have a lower version? I'd like to have an as broad as possible compatibility. 2022.3﻿ seems to be the version when `getActionUpdateThread` was introduced and I was able to build with that version (and also setting `sinceBuild.set` to 223)

2024-04-19 22:31 UTC, silvasur commented on src/main/resources/META-INF/pluginIcon.svg
What's the license for this file? Can this just be imported into this repo without any legal issues? If in doubt, I'd prefer to just stay without an icon, it's not really needed for the plugin.

2024-04-19 22:31 UTC, silvasur commented on build.gradle.kts
> +        untilBuild.set("500.*")
Why is this needed?

2024-04-20 08:20 UTC, d3v2a commented on gradle/wrapper/gradle-wrapper.jar
Just create a new plugin with idea and do a diff, it was generated by the ide

2024-04-20 08:27 UTC, d3v2a commented on build.gradle.kts
> +        untilBuild.set("500.*")
This is the max version compatible and is required.

2024-04-20 08:29 UTC, d3v2a commented on src/main/resources/META-INF/pluginIcon.svg
The License is in src/main/resources/META-INF/plugin.xml line 38.

2024-04-20 10:06 UTC, d3v2a commented on build.gradle.kts
> +    version.set("2023.2.5")
Added in last commit

2024-04-23 20:30 UTC, silvasur commented on gradle/wrapper/gradle-wrapper.jar
Ah I see, confirmed :)

2024-04-23 20:31 UTC, silvasur commented on build.gradle.kts
> +    version.set("2023.2.5")
Thanks!

2024-04-23 20:31 UTC, silvasur commented on src/main/resources/META-INF/pluginIcon.svg
Ah okay, I checked svgrepo now and apparently that short line is really all that is necessary. Then this is OK :)

2024-04-23 20:32 UTC, silvasur commented on build.gradle.kts
> +        untilBuild.set("500.*")
Okay, I see. If the current versioning scheme is kept, we're good until 2050, so that's fine by me :).

2024-04-23 20:39 UTC, silvasur approved these changes
Looks good to me now, will merge it. Thank you for your merge request! If you'd like, I'll add a `CONTRIBUTORS` file to credit you a bit more explicitly than just in the git commit authorship data. If you'd like that, please reply to me, which name and URL (if you want) I should put there :)

2024-04-23 20:43 UTC, merged

2024-04-23 20:47 UTC, silvasur commented
I've now merged it and submitted the new plugin version to the jetbrains marketplace, might take a while for it to get approved.